### ISSUE TITLE
ReadFile is bug 

### ISSUE THREAD

**Issue by jackluo2012** [narup/gmgo#1]
func (s *DbSession) ReadFile(id, prefix string, file *File) error {
	f, err := s.gridFS(prefix).OpenId(bson.ObjectIdHex(id))
	if err != nil {
		return err
	}
	n := file.ByteLength
	if n == 0 {
		n = 8192
	}
	b := make([]byte, file.ByteLength)
	_, err = f.Read(b)

	err = f.Close()
	if err != nil {
		return err
	}

	file.ID = id
	file.Data = b
	file.Name = f.Name()
	file.ContentType = f.ContentType()

	return nil
}
----------------------------------------------------------
It's Me
//ReadFile read file based on given id
func (s *DbSession) ReadFile(id, prefix string, file *File) error {
	f, err := s.gridFS(prefix).OpenId(bson.ObjectIdHex(id))
	if err != nil {
		return err
	}
	n := file.ByteLength
	if n == 0 {
		n = 8192
	}
	buf := make([]byte,n)
	chunks := make([]byte,f.Size())
	for{
		n, err := f.Read(buf)
		if err != nil && err != io.EOF{
			return err
		}
		if 0 ==n {break}
		chunks=append(chunks,buf[:n]...)
	}

	err = f.Close()
	if err != nil {
		return err
	}

	file.ID = id
	file.Data = chunks
	file.Name = f.Name()
	file.ContentType = f.ContentType()

	return nil
}

**Comment by narup** [comment]
Ah, Thanks @jackluo2012 I will take a look and fix it

**Comment by jackluo2012** [comment]
Fork 
https://github.com/jackluo2012/gmgo.git
